-- 1. CONFIGURACIÓN INICIAL (ENUMS)
CREATE TYPE user_role AS ENUM ('admin', 'doctor', 'patient', 'caretaker');
CREATE TYPE relationship_status AS ENUM ('pending', 'active', 'rejected');
CREATE TYPE relationship_type AS ENUM ('doctor_patient', 'caretaker_patient');

-- 2. TABLA DE PERFILES 
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  role user_role NOT NULL DEFAULT 'patient',
  first_name TEXT,
  last_name TEXT,
  curp TEXT UNIQUE, -- para vincular Cuidador-Paciente 
  phone TEXT,
  birth_date DATE,
  cedula_profesional TEXT, -- Solo para Médicos
  subscription_status TEXT DEFAULT 'active', -- Para el pago y acceso a funciones premium
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. TABLA DE VINCULACIONES 
-- Une Paciente con Médico y Paciente con Cuidador.
CREATE TABLE public.relationships (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  patient_id UUID REFERENCES public.profiles(id) NOT NULL,
  agent_id UUID REFERENCES public.profiles(id) NOT NULL, -- Puede ser Doctor o Cuidador
  type relationship_type NOT NULL,
  status relationship_status DEFAULT 'pending', -- El médico/paciente debe aceptar
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(patient_id, agent_id) -- Evita duplicados
);

-- 4. TABLA DE TOKENS DEXCOM (Para el Sandbox IoT)
-- Aquí guardamos las llaves para que tu backend "hackee" el sensor.
CREATE TABLE public.dexcom_tokens (
  user_id UUID REFERENCES public.profiles(id) PRIMARY KEY,
  access_token TEXT NOT NULL,
  refresh_token TEXT NOT NULL, -- Vital para refrescar la conexión cada hora
  expires_at TIMESTAMP WITH TIME ZONE,
  dexcom_user_id TEXT, -- El ID que te da Dexcom (ej. "SandboxUser1")
  last_sync TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. TABLA DE LECTURAS DE GLUCOSA (IoT Data)
-- Donde se guardan los millones de datos.
CREATE TABLE public.glucose_readings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id UUID REFERENCES public.profiles(id) NOT NULL,
  value INTEGER NOT NULL, -- Ej: 120 (mg/dL)
  trend TEXT, -- Ej: "flat", "rising", "falling" (Flechas de tendencia Dexcom)
  timestamp TIMESTAMP WITH TIME ZONE NOT NULL, -- Hora exacta de la lectura
  source TEXT DEFAULT 'dexcom_sandbox', -- Para saber si vino del sensor o manual
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexamos por tiempo y paciente para que las gráficas carguen rápido
CREATE INDEX idx_glucose_patient_time ON public.glucose_readings (patient_id, timestamp DESC);

-- 6. TABLA DE CHAT (Mensajería)
-- Comunicación Doctor-Paciente.
CREATE TABLE public.chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID REFERENCES public.profiles(id) NOT NULL,
  receiver_id UUID REFERENCES public.profiles(id) NOT NULL,
  content TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE, -- Para el doble check azul
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. TABLA DE CITAS Y DIAGNÓSTICOS (Historial Clínico)
-- 
CREATE TABLE public.clinical_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id UUID REFERENCES public.profiles(id) NOT NULL,
  doctor_id UUID REFERENCES public.profiles(id) NOT NULL,
  type TEXT NOT NULL, -- 'cita', 'diagnostico', 'receta'
  title TEXT, -- Ej: "Consulta Mensual" o "Metformina 500mg"
  description TEXT,
  scheduled_at TIMESTAMP WITH TIME ZONE, -- Solo para citas
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. FUNCIÓN AUTOMÁTICA (Trigger)
-- crea un perfil vacío automáticamente cada vez que alguien se registra en Auth.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role, first_name, curp)
  VALUES (
    new.id, 
    new.email, 
    COALESCE((new.raw_user_meta_data->>'role')::user_role, 'patient'),
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'curp'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 9. ACTIVAR SEGURIDAD (RLS)
-- Por defecto nadie puede ver nada. Hay que crear políticas después.
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.glucose_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;